name: CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        java: [8, 9, 11, 14]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name:
        run: chmod +x gradlew
      - name: Launch MongoDB
        uses: wbari/start-mongoDB@v0.2
        with:
          mongoDBVersion: 4.2
      - name: Build
        run: ./gradlew assemble
      - name: Tests
        run: ./gradlew check
